version: "3"
services: 
  react-app: 
    image: react-app
    build: ./client/
    ports:
      - "3000:3000"
    stdin_open: true
    networks: 
      - mern-app
    volumes: 
      - ./client/:/src/app
      - /src/node_modules
    depends_on:
      - react-server
  react-server: 
    image: react-server
    build: ./server/
    ports: 
      - "8080:8080"
    networks:
      - mern-app
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://*:*@cluster0.mxvalai.mongodb.net/quizzappdb
    volumes: 
      - ./server/:/src/app
      - /src/node_modules
  mongodb: 
    image: mongo:latest 
    ports: 
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_USERNAME=*
      - MONGO_PASSWORD=*
networks: 
  mern-app: 
    driver: bridge
volumes:
  mongo-data: 
    driver: local

